name: 'Self-labelling'
on: [pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: 1138-4EB/actions@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
